[package]
name = "citext"
version = "0.3.1"
compiler = "0.14.2"
entrypoint = "lib.typ"
authors = ["Shuenhoy"]
license = "MIT"
description = "Use citation.js for CSL-M and citep"

repository = "https://github.com/Shuenhoy/citext"

keywords = ["javascript", "citation"]
